/*
 Generated by typeshare 1.0.0
 */

import Foundation

public struct MyStruct: Codable {
	public let my_name: String
	public let my_age: UInt32

	public init(my_name: String, my_age: UInt32) {
		self.my_name = my_name
		self.my_age = my_age
	}
}
